---
- name: Create DNS IPv4 record
  delegate_to: localhost
  community.dns.hetzner_dns_record_set:
    hetzner_token: "{{ hetzner_dns_token }}"
    zone: "{{ hetzner_dns_zone }}"
    record: "{{ item }}.{{ hetzner_dns_zone }}"
    type: A
    ttl: "{{ dns_default_ttl }}"
    value: "{{ host_external_ipv4 }}"
    state: present
  when: (host_external_ipv4 | default('')) | length > 0
  with_items: "{{ subdomains | list }}"

- name: Create DNS IPv6 record
  delegate_to: localhost
  community.dns.hetzner_dns_record_set:
    hetzner_token: "{{ hetzner_dns_token }}"
    zone: "{{ hetzner_dns_zone }}"
    record: "{{ item }}.{{ hetzner_dns_zone }}"
    type: AAAA
    ttl: "{{ dns_default_ttl }}"
    value: "{{ host_external_ipv6 }}"
    state: present
  when: (host_external_ipv6 | default('')) | length > 0
  with_items: "{{ subdomains | list }}"