version: '3'

services:
  memos:
    image: neosmemo/memos:stable
    restart: always
    ports:
      - "127.0.0.1:5230:5230"
    environment:
      - MEMOS_MODE=prod
      - MEMOS_ADDR=0.0.0.0
      - MEMOS_PORT=5230
      - MEMOS_DATA=/var/opt/memos
      - MEMOS_DRIVER=sqlite
      - MEMOS_DSN=
      # Enable local authentication
      - MEMOS_AUTH_LOCAL_ENABLED=false
      # Allow user registration
      - MEMOS_ALLOW_SIGNUP=false
      # Require email verification
      - MEMOS_REQUIRE_EMAIL_VERIFICATION=false
      # Admin approval for new users
      - MEMOS_REQUIRE_ADMIN_APPROVAL=true
      # Mail config
      - MEMOS_SMTP_HOST=host.containers.internal
      - MEMOS_SMTP_PORT=25
      - MEMOS_SMTP_USERNAME=
      - MEMOS_SMTP_PASSWORD=
      - MEMOS_SMTP_FROM={{ postfix_mail_address }}
      # Custom OAuth
      - MEMOS_OAUTH_CUSTOM_ENABLED=true
      - MEMOS_OAUTH_CUSTOM_NAME=Authelia
      - MEMOS_OAUTH_CUSTOM_CLIENT_ID=memos
      - MEMOS_OAUTH_CUSTOM_CLIENT_SECRET={{ authelia_memos_client_secret }}
      # OAuth endpoints
      - MEMOS_OAUTH_CUSTOM_AUTH_URL=https://{{ auth_subdomain }}.{{ hetzner_dns_zone }}/api/oidc/authorization
      - MEMOS_OAUTH_CUSTOM_TOKEN_URL=https://{{ auth_subdomain }}.{{ hetzner_dns_zone }}/api/oidc/token
      - MEMOS_OAUTH_CUSTOM_USER_URL=https://{{ auth_subdomain }}.{{ hetzner_dns_zone }}/api/oidc/userinfo
      # Attribute mapping
      - MEMOS_OAUTH_CUSTOM_USERNAME_ATTR=preferred_username
      - MEMOS_OAUTH_CUSTOM_EMAIL_ATTR=email
      - MEMOS_OAUTH_CUSTOM_NAME_ATTR=name
      # Timezone
      - TZ=Europe/Berlin

    volumes:
      - memos-volume:/var/opt/memos
  mortis:
    image: ghcr.io/mudkipme/mortis:0.25.0
    restart: always
    ports:
      - "127.0.0.1:5231:5231"
    entrypoint: ["/app/mortis"]
    command: ["-grpc-addr=memos:5230"]
    depends_on:
      - memos
volumes:
  memos-volume:
    driver_opts:
      type: none
      device: {{ container_volumes_dir }}/{{ compose_volumes[0] }}
      o: bind
