- name: Restart prometheus-pushgateway
  service:
    name: prometheus-pushgateway
    state: restarted
    enabled: yes
  become: yes

- name: Restart prometheus-node-exporter
  service:
    name: prometheus-node-exporter
    state: restarted
    enabled: yes
  become: yes

- name: Restart prometheus-nginx-exporter
  service:
    name: prometheus-nginx-exporter
    state: restarted
    enabled: yes
  become: yes